Models/Calculadora.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TP_Calculadora.Models
{
   public static class Calculadora
   {
      public static double numero1 {get;set;}

      public static double numero2 {get;set;}

      public static double multiplicacion(double numero1, double numero2)
      {
        double resultado = 0;
        resultado = numero1 * numero2;
        return resultado;
      }

      public static double division(double numero1, double numero2)
      {
        double resultado = 0;
        resultado = numero1 / numero2;
        return resultado;
      }

      public static double suma(double numero1, double numero2)
      {
        double resultado = 0;
        resultado = numero1 + numero2;
        return resultado;
      }

      public static double resta(double numero1, double numero2)
      {
        double resultado = 0;
        resultado = numero1 - numero2;
        return resultado;
      }
   }
}

Models/ErrorViewModel.cs
namespace TP_Calculadora.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Controllers/CalculadoraController.cs
using Microsoft.AspNetCore.Mvc;
using System.Text.Encodings.Web;
using TP_Calculadora.Models;

namespace TP_Calculadora.Controllers
{
    public class CalculadoraController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        
        public IActionResult Calculo(string operacion, double numero1, double numero2)
        {
            switch(operacion){
                case "Multiplicacion":
                    ViewBag.resultado = Calculadora.multiplicacion(numero1, numero2);
                break;
                case "Division":
                    ViewBag.resultado = Calculadora.division(numero1, numero2);
                break;
                case "Suma":
                    ViewBag.resultado = Calculadora.suma(numero1, numero2);
                break;
                case "Resta":
                    ViewBag.resultado = Calculadora.resta(numero1, numero2);
                break;
            }
            return View();
        }
        
    }
}

Views/Calculadora/Calculo.cshtml
@{
    ViewData["Title"] = "Resultado";
}
<div class="text-center">
    <h1> El resultado es:  </h1>
       <h1>@ViewBag.resultado</h1>
    <form asp-controller="Calculadora" asp-action="Index" method = "post">
    <p><input type = "submit" value = "Volver"></p>
    </form>
</div>

Views/Calculadora/Index.cshtml
@{
    ViewData["Title"] = "Calculadora";
}
<div class="text-center">
    <h1> Calculadora </h1>
    <form asp-controller="Calculadora" asp-action="Calculo" method = "post">
    <div>
        <p><b>Elegir el tipo de operacion: </b></p>
        <select name="operacion" id="TipoOperacion">
            <option value = "Multiplicacion"> Multiplicacion </option>
            <option value = "Division">Division</option>
            <option value = "Suma">Suma</option>
            <option value = "Resta">Resta</option>
        </select>
    </div>
    <div>
        <p><b>Numero 1</b></p>
        <input type="number" name = "numero1"><br>
    </div>
    <div>
        <p><b>Numero 2</b></p>
        <input type="number" name = "numero2"><br>
    </div>
    <p><input type = "submit" value = "Calcular"></p>
    </form>
</div>

@if (ViewBag.Resultado != 0)
{
    <div>
        <h2>@ViewBag.Resultado</h2>
    </div>
}


Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Resultado";
}
<div class="text-center">
    <h1> El resultado es:  </h1>
       <h1>@ViewBag.resultado</h1>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TP_Calculadora</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TP_Calculadora.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Calculadora" asp-action="Index">TP_Calculadora</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Calculadora" asp-action="Index">Calculadora</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - TP_Calculadora - <a asp-area="" asp-controller="Calculadora" asp-action="Index">Calculadora</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>